### ISSUE TITLE
pergunta sobre o UTF-8.

### ISSUE THREAD

**Issue by kalebzaki4** [MonicaHillman/code-connect-login-project#1]
para que serve o UTF-8?

**Comment by MonicaHillman** [comment]
UTF-8 é "Unicode Transformation Format - 8 bits". Ele é um sistema de codificação de caracteres, serve para representar e codificar caracteres de texto de diferentes idiomas e símbolos de forma que possam ser exibidos e processados corretamente em dispositivos. Isso garante que o navegador saiba como interpretar e exibir os caracteres no documento corretamente, independentemente do idioma em que estão escritos.
